### PR TITLE
docs: add ecommerce v2 example

### PR DESCRIPTION
**Pull request by zlatanpham**
Migrate the eCommerce demo using v1 API to use v2:

- [x] Use v2 API
- [x] 100% use hooks
- [x] TypeScript
- [x] Preact CLI to NextJS 
- [ ] Use new Tracking API
- [ ] ~Sajari-UI to Tailwind v3~

```sh
# Build command
yarn build

# Distributed folder
./out
```

### CODE REVIEW

**Comment by zlatanpham** [comment]
@wwalser I was trying to migrate the source away from sajari-ui and then upgrade tailwind v3 but the work would take a couple of days so I think we should wrap it up at this stage. (Was trying to use vitejs too but got a mess with PostCSS).

**Review by wwalser — APPROVED** [review]

**Comment by wwalser** [comment]
> Was trying to use vitejs too but got a mess with PostCSS

Yeah, Vite requires a soft touch when pairing it with some tools still.

**Comment by wwalser** [comment]
Happy to move forward with this 👍

**Comment by wwalser** [comment]
SF-871
SF-876
SF-873
SF-875

**Comment by justinkoke** [comment]
SF-871
SF-876
SF-873
SF-875

**Review by wwalser — APPROVED** [review]

**Comment by wwalser** [comment]
I believe the PR which this was waiting on is now merged.

**Pull request merged**
